### ISSUE TITLE
Can't make it work!

### ISSUE THREAD

**Issue by poblom** [denniedegroot/com.apc.ups#1]
I have apcupsd set up on an rpi, as well as the web interface. Trying to create a device in Homey but I get "No new devices found". Me doing something wrong or this app needs some love?

P.S Nothing to find in my firewall log

/PO

**Comment by poblom** [comment]
Problem solved!

Neded to set NSIP to 0.0.0.0 in apcups.conf and reboot!

/PO

**Comment by maheldt** [comment]
How do you config apcups.conf ?

**Comment by poblom** [comment]
As far as I can recall the only change I did was as in the comment above. Apart from that default settings.

/PO

**Comment by maheldt** [comment]
okey, did you do that via cli against homey?

**Comment by poblom** [comment]
No, I edited the file on the computer (a raspberrypi) where apcups is running. The file is located at /etc/apcupsd/apcupsd.conf 

/PO

**Comment by maheldt** [comment]
okey, thx :)

**Comment by poblom** [comment]
I had to restart not only the daemon but the computer for the change to take effect.

/PO
