### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by christian-ek** [denniedegroot/com.apc.ups#2]
Hi!
I am trying to install on my Homey but I get the following error:
This app is incompatible with your Homey software version.

I have version 2.0.4

**Comment by denniedegroot** [comment]
I just submitted a new version to the app store which will solve this problem.

**Comment by christian-ek** [comment]
Thanks! Seems like I have to wait for it to be merged or something cause it's still at version 1.0.0 for me in the app store.

**Comment by denniedegroot** [comment]
It is available now.
