### ISSUE TITLE
Supported APS Models

### ISSUE THREAD

**Issue by johngrinders** [denniedegroot/com.apc.ups#5]
Hey. I'm sorry to trouble you. I wanted to know what devices (models) or characteristics APC UPS supports the plugin for Homey? I just want to buy APC UPS, and then the question immediately arises of what exactly is needed. Thank!!!

**Comment by denniedegroot** [comment]
Well every unit should be supported if its supported by the apcupsd tool.
Note that the ups does not directly interfaces with Homey but via apcupsd.
